import type { Metadata } from "next";
import { PageLayout } from "@/components/PageLayout";

export const metadata: Metadata = {
  title: "Terms of Service — ListingBoost AI",
  description:
    "Read the terms and conditions for using ListingBoost AI's product listing generation service. Understand your rights and obligations.",
  alternates: { canonical: "/terms-of-service" },
};

export default function TermsOfServicePage() {
  return (
    <PageLayout>
      <section className="pt-28 pb-16 sm:pt-32 sm:pb-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <div className="mb-12">
            <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">
              Terms of Service
            </h1>
            <p className="mt-3 text-sm text-muted-foreground">
              Last updated: May 15, 2026
            </p>
          </div>

          {/* Content */}
          <div className="prose prose-sm sm:prose max-w-none text-muted-foreground [&_h2]:text-foreground [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-10 [&_h2]:mb-4 [&_p]:leading-relaxed [&_ul]:space-y-2 [&_li]:leading-relaxed">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using ListingBoost AI (the &quot;Service&quot;), available at{" "}
              <a
                href="https://ealoongchan.top"
                className="text-primary hover:underline"
              >
                ealoongchan.top
              </a>
              , you accept and agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do
              not agree to these Terms, you must not use the Service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              ListingBoost AI provides an artificial intelligence-powered tool that generates
              product listing content for e-commerce platforms, including but not limited to product
              titles, bullet points, and product descriptions. The Service is provided &quot;as is&quot; and
              &quot;as available&quot; without warranties of any kind.
            </p>

            <h2>3. User Responsibilities</h2>
            <p>When using the Service, you agree to:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                Provide accurate and lawful product information as input for listing generation.
              </li>
              <li>
                Review and edit all AI-generated content before publishing it to any e-commerce
                platform.
              </li>
              <li>Not use the Service for any unlawful, fraudulent, or deceptive purposes.</li>
              <li>
                Not generate content that infringes upon the intellectual property rights of any
                third party.
              </li>
              <li>
                Not use the Service to create misleading, false, or deceptive product listings.
              </li>
              <li>
                Comply with the terms of service and policies of all e-commerce platforms where you
                publish generated content.
              </li>
            </ul>

            <h2>4. AI-Generated Content Disclaimer</h2>
            <p>
              <strong className="text-foreground">Important:</strong> The content generated by our
              AI is provided for informational and drafting purposes only. You are solely responsible
              for:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Verifying the accuracy and completeness of all generated content</li>
              <li>Ensuring generated content complies with applicable laws and regulations</li>
              <li>
                Confirming that claims made in generated content are truthful and substantiated
              </li>
              <li>
                Ensuring generated content does not violate the policies of any e-commerce platform
              </li>
              <li>Obtaining any necessary approvals or certifications mentioned in the content</li>
            </ul>
            <p>
              ListingBoost AI does not guarantee that the generated content will result in increased
              sales, improved rankings, or any specific commercial outcome.
            </p>

            <h2>5. Intellectual Property</h2>
            <p>
              The Service, including its original content, features, and functionality, is owned by
              ListingBoost AI and is protected by international copyright, trademark, patent, trade
              secret, and other intellectual property laws.
            </p>
            <p>
              You retain ownership of the product information you input and the AI-generated listings
              produced from your input. However, by using the Service, you grant us a limited,
              non-exclusive license to process your input data for the purpose of generating listings.
            </p>

            <h2>6. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, ListingBoost AI shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages, including
              but not limited to loss of profits, data, use, goodwill, or other intangible losses,
              resulting from:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Your use of or inability to use the Service</li>
              <li>Any errors, inaccuracies, or omissions in AI-generated content</li>
              <li>Any unauthorized access to or alteration of your data</li>
              <li>Any other matter relating to the Service</li>
            </ul>

            <h2>7. Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless ListingBoost AI and its officers,
              directors, employees, and agents from and against any claims, liabilities, damages,
              losses, and expenses arising out of or in any way connected with your access to or use
              of the Service or your violation of these Terms.
            </p>

            <h2>8. Modifications to the Service</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue the Service (or any part
              thereof) at any time without notice. We shall not be liable to you or any third party
              for any modification, suspension, or discontinuation of the Service.
            </p>

            <h2>9. Changes to These Terms</h2>
            <p>
              We reserve the right to revise these Terms at any time. Changes will be effective
              immediately upon posting on this page with an updated &quot;Last updated&quot; date. Your
              continued use of the Service after any changes constitutes your acceptance of the new
              Terms.
            </p>

            <h2>10. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable laws,
              without regard to conflict of law principles. Any disputes arising from these Terms or
              the Service shall be resolved through good-faith negotiation.
            </p>

            <h2>11. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at{" "}
              <a
                href="mailto:support@listingboost.ai"
                className="text-primary hover:underline"
              >
                support@listingboost.ai
              </a>
              .
            </p>
          </div>
        </div>
      </section>
    </PageLayout>
  );
}
